services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=192.168.0.4
      - DB_PORT=5432
      - DB_USER=pixel_battle_db_user
      - DB_PASSWORD=4>pf4ZR&J4Wp6e
      - DB_NAME=pixel_battle
      - ADMIN_PASSWORD=adminnesosal85780957
      - PORT=3000
    ports:
      - "8888:3000"
    restart: unless-stopped
