version: '3.8'

services:
  # Наша база данных PostgreSQL (ДАННЫЕ НЕ СОХРАНЯЮТСЯ ПРИ ПЕРЕЗАПУСКЕ)
  db:
    image: postgres:15-alpine
    container_name: pixel-battle-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersecretpassword # Замените на надежный пароль
      POSTGRES_DB: pixelbattle
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Наш Node.js сервер с WebSockets
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: pixel-battle-app
    environment:
      - DB_USER=admin
      - DB_PASSWORD=supersecretpassword
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=pixelbattle
      - ADMIN_PASSWORD=supersecretadmin123 # <-- Пароль для входа в админку
    ports:
      - "8080:3000"
    depends_on:
      - db
    restart: unless-stopped