server {
listen 80;

# Замените на ваш реальный домен, например: pixelbattle.ru www.pixelbattle.ru
server_name localhost; 

# Корневая папка, где лежит index.html
root /usr/share/nginx/html;
index index.html;

# Базовая настройка
location / {
    try_files $uri $uri/ /index.html;
}

# Включаем GZIP сжатие для ускорения загрузки
gzip on;
gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

# Запрещаем кэширование самого HTML, чтобы обновления доходили до пользователей мгновенно
location ~* \.html$ {
    expires -1;
    add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
}


}